const utils = require('../utils/utils');
const t_travelNotesImage = {
	notes_img_id:{
		name:'notes_img_id',
		type:'int',
		isNull:false,
		length:10
	},
	notes_img_tid:{
		name:'notes_img_tid',
		type:'int',
		isNull:false,
		length:10
	},
	notes_img_url:{
		name:'notes_img_url',
		type:'string',
		isNull:false,
		length:255
	},
	notes_img_description:{
		name:'notes_img_description',
		type:'string',
		isNull:false,
		length:255
	},
	notes_img_createDate:{
		name:'notes_img_createDate',
		type:'date',
		isNull:true,
		length:0
	},
	notes_img_editDate:{
		name:'notes_img_editDate',
		type:'date',
		isNull:true,
		length:0
	},
	notes_img_type:{
		name:'notes_img_type',
		type:'string',
		isNull:true,
		length:255
	},
	notes_img_width:{
		name:'notes_img_width',
		type:'int',
		isNull:true,
		length:11
	},
	notes_img_height:{
		name:'notes_img_height',
		type:'int',
		isNull:true,
		length:11
	},
	notes_img_size:{
		name:'notes_img_size',
		type:'int',
		isNull:true,
		length:11
	}
}